### ISSUE TITLE
vsphere-csi pods issue with liveness probe syntax (port defined as healthz)

### ISSUE THREAD

**Issue by plaes** [vsphere-tmm/helm-charts#59]
When setting up vsphere-csi via the helm chart, vsphere-csi pods show following in the events:
`Liveness probe errored: strconv.Atoi: parsing "healthz": invalid syntax`

This seems to be coming from vsphere-csi-node container definition:
```
Containers:
  vsphere-csi-node:
    Container ID:  containerd://...
    Image:         gcr.io/cloud-provider-vsphere/csi/release/driver:v3.0.0
    Image ID:      gcr.io/cloud-provider-vsphere/csi/release/driver@sha256:4f15947d7a901e3b2f37783ae325d44022d6ee8427af17142fc7a550d3693172
    Port:          <none>
    Host Port:     <none>
    Args:
      --fss-name=internal-feature-states.csi.vsphere.vmware.com
      --fss-namespace=$(CSI_NAMESPACE)
    State:          Running
      Started:      Thu, 23 Mar 2023 18:16:49 +0200
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:healthz/healthz delay=10s timeout=5s period=5s #success=1 #failure=3
```

**Comment by sathieu** [comment]
Named port [should be possible](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#use-a-named-port). :no_good:

**Comment by sathieu** [comment]
The node Pod have:

```yaml
          ports:  # <<<< EMPTY
          resources:
            limits: {}
            requests: {}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
```

While the controller pods have:

```yaml
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 25
            periodSeconds: 5
            timeoutSeconds: 3
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
            - name: prometheus
              containerPort: 2112
              protocol: TCP
```

node has the [following](https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/fdbf3820ae62e8e2f422bec4b67aaf6240b6ed2e/manifests/vanilla/vsphere-csi-driver.yaml#L520-L527) upstream:



```yaml
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
 ```

I'll create a PR.
