### ISSUE TITLE
DaemonSet updateStrategy

### ISSUE THREAD

**Issue by jda258** [vsphere-tmm/helm-charts#66]
Hello,

Is there a reason for this DaemonSet updateStrategy:
```
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```

These settings make it take a long time to update for larger clusters. Is there a better default setting, or should it be added to the values file?

Thanks,
Josh
